spring:
  datasource:
    url: 'jdbc:h2:mem:BDD_AKDMIA;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDMIA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:

  jpa:
    generate-ddl: true #change to false in production mode
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: 'BDD_AKDMIA'

  sql:
    init:
      platform: h2

  web:
    allowed-origins: http://localhost:5173

components:
  jwt:
    secret-key: "4kdm144kdm144kdm144kdm144kdm144kdm144kdm144kdm14"
    deprecation-time: 28800000 #8 hours expressed in milis
    #eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkJhZWxkdW5nIFVzZXIiLCJpYXQiOjE1MTYyMzkwMjJ9.L5zvFL9qWykT7xOI8CUhlDHI9n67eAhllc9ZV-eQLtk

logging:
  level:
    org.springframework.security: TRACE