spring:
  datasource:
    url: 'jdbc:h2:mem:BDD_AKDMIA;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDMIA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:

  jpa:
    generate-ddl: true #change to false in production mode
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: 'BDD_AKDMIA'

  sql:
    init:
      platform: h2
